---
- hosts: all
  vars:
    jfrogcli_ver:
      major: 1
      minor: 49
      patch: 0
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jfrog --version
      register: jfrogcli_test_output
    - debug:
        msg: '{{ jfrogcli_test_output.stdout }}'
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jfrog --version
      register: jfrogcli_test_output
    - debug:
        msg: '{{ jfrogcli_test_output.stdout }}'
