---
- name: Testing andrewrothstein.jfrogcli (v1)
  hosts: all
  vars:
    jfrogcli_ver:
      major: 1
      minor: 49
      patch: 0
  tasks:
    - name: Installing andrewrothstein.jfrogcli (v1)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'jfrog --version'
      ansible.builtin.command: /usr/local/bin/jfrog --version
      changed_when: false
      register: jfrogcli_test_output
    - name: Output from 'jfrog --version'
      ansible.builtin.debug:
        msg: '{{ jfrogcli_test_output.stdout }}'
- name: Testing andrewrothstein.jfrogcli (v2)
  hosts: all
  tasks:
    - name: Installing andrewrothstein.jfrogcli (v2)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'jfrog --version'
      ansible.builtin.command: /usr/local/bin/jfrog --version
      changed_when: false
      register: jfrogcli_test_output
    - name: Output from 'jfrog --version'
      ansible.builtin.debug:
        msg: '{{ jfrogcli_test_output.stdout }}'
