---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/jfrog --version
      register: jfrogcli_test_output
    - debug:
        msg: '{{ jfrogcli_test_output.stdout }}'
