---
- name: downloading {{ jfrogcli_url }} to {{ jfrogcli_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ jfrogcli_url }}'
    dest: '{{ jfrogcli_exe }}'
    mode: 0755
- name: linking {{ jfrogcli_link }} to {{ jfrogcli_exe }}
  become: true
  become_user: root
  file:
    src: '{{ jfrogcli_exe }}'
    dest: '{{ jfrogcli_link }}'
    state: link
