---
- name: Downloading {{ jfrogcli_url }} to {{ jfrogcli_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ jfrogcli_url }}'
    dest: '{{ jfrogcli_exe }}'
    mode: '755'
- name: Linking {{ jfrogcli_link }} to {{ jfrogcli_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ jfrogcli_exe }}'
    dest: '{{ jfrogcli_link }}'
    state: link
