---
- name: downloading {{ jfrogcli_exe_url }} to {{ jfrogcli_target_exe }}
  become: yes
  become_user: root
  get_url:
    url: '{{ jfrogcli_exe_url }}'
    dest: '{{ jfrogcli_target_exe }}'
    mode: 0755
- name: linking {{ jfrogcli_target_link }} to {{ jfrogcli_target_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ jfrogcli_target_exe }}'
    dest: '{{ jfrogcli_target_link }}'
    state: link
